# Generated by Django 3.1.2 on 2020-11-04 09:06

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='groups'),
        ),
    ]
