# Generated by Django 3.1.2 on 2020-11-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201103_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='cats',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cats', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts', verbose_name='Картинка'),
        ),
    ]
